### ISSUE TITLE
mkdir error

### ISSUE THREAD

**Issue by JimnyCricket** [dfst/deepforge#643]
`Error: ENOENT: no such file or directory, mkdir '/usr/local/lib/node_modules/deepforge/s
rc/worker/tmp'                                                                          
    at Error (native)                                                                   
    at Object.fs.mkdirSync (fs.js:916:18)                                               
    at /usr/local/lib/node_modules/deepforge/node_modules/webgme/src/server/middleware/e
xecutor/worker/node_worker.js:221:20                                                    
    at next (/usr/local/lib/node_modules/deepforge/node_modules/webgme/src/server/middle
ware/executor/worker/node_modules/rimraf/rimraf.js:74:7)                                
    at CB (/usr/local/lib/node_modules/deepforge/node_modules/webgme/src/server/middlewa
re/executor/worker/node_modules/rimraf/rimraf.js:110:9)                                 
    at /usr/local/lib/node_modules/deepforge/node_modules/webgme/src/server/middleware/e
xecutor/worker/node_modules/rimraf/rimraf.js:136:14                                     
    at FSReqWrap.oncomplete (fs.js:117:15)                                              
2016-08-09T15:26:16.841Z - info: [gme:serv`

**Comment by brollb** [comment]
worker should have a (configurable) tmp dir in `~/.deepforge/worker/tmp`
