### ISSUE TITLE
Error on All Executions Page when multiple jobs are running

### ISSUE THREAD

**Issue by JimnyCricket** [dfst/deepforge#753]
```
:9898/dist/webgme.dist.build.js:13 hashUpdateHandler invoked loading and it returned error #41d024101758ff8e1e07957956ccd4541bce5925 Error: ASSERT failed(…)o.error @ :9898/dist/webgme.dist.build.js:13
:9898/dist/webgme.dist.build.js:13 state at hashUpdateHandler {"connection":"CONNECTED","projectId":"guest+FreqDrop","branchName":"master","branchStatus":"PULLING","commitHash":"#2921a3845ce83c14bb9dc4ba07fe53ff6306edc7","rootHash":"#41d024101758ff8e1e07957956ccd4541bce5925","projectReadOnly":false,"commitReadOnly":false}o.error @ :9898/dist/webgme.dist.build.js:13
:9898/dist/webgme.dist.build.js:13 Loading of update commit failed with error Error: ASSERT failed(…) Objecto.error @ :9898/dist/webgme.dist.build.js:13
5:9898/dist/webgme.dist.build.js:14 Throwing Error: ASSERT failed
    at t (http://10.101.49.17:9898/dist/webgme.dist.build.js:14:22009)
    at r.loadByPath (http://10.101.49.17:9898/dist/webgme.dist.build.js:19:2949)
    at Function.<anonymous> (http://10.101.49.17:9898/dist/webgme.dist.build.js:21:265)
    at Object.S [as call] (http://10.101.49.17:9898/dist/webgme.dist.build.js:18:9803)
    at r.loadByPath (http://10.101.49.17:9898/dist/webgme.dist.build.js:21:240)
    at http://10.101.49.17:9898/dist/webgme.dist.build.js:18:30287
    at t.tasync_unwraped.t.tasync_unwraped (http://10.101.49.17:9898/dist/webgme.dist.build.js:18:5366)
    at n.loadByPath (http://10.101.49.17:9898/dist/webgme.dist.build.js:22:1936)
    at L (http://10.101.49.17:9898/dist/webgme.dist.build.js:24:12684)
    at h.execute (http://10.101.49.17:9898/dist/webgme.dist.build.js:18:10805)
    at http://10.101.49.17:9898/dist/webgme.dist.build.js:18:6056
```

**Comment by brollb** [comment]
This seems to happen when a graph is created but has no lines/data yet
