### ISSUE TITLE
Error and crash when downloading exported branch

### ISSUE THREAD

**Issue by SeanNaren** [dfst/deepforge#890]
When I export my branch (which seems to be successful) and try to download it by clicking the link, after a while this crashes with the below error and the server stops responding:

```
2016-11-14T13:12:51.735Z - error: uncaughtException: Invalid typed array length
{ date: 'Mon Nov 14 2016 13:12:51 GMT+0000 (UTC)',
  process:
   { pid: 31753,
     uid: 1002,
     gid: 1002,
     cwd: '/home/sean.narenthiran/deepforge',
     execPath: '/usr/bin/nodejs',
     version: 'v4.6.0',
     argv: [ '/usr/bin/nodejs', '/home/sean.narenthiran/deepforge/app.js' ],
     memoryUsage: { rss: 6751166464, heapTotal: 49936736, heapUsed: 39125952 } },
  os:
   { loadavg: [ 1.2802734375, 0.5419921875, 0.23193359375 ],
     uptime: 2173354 },
  trace:
   [ { column: null,
       file: null,
       function: 'new Uint8Array',
       line: null,
       method: null,
       native: true },
     { column: 17,
       file: '/home/sean.narenthiran/deepforge/node_modules/webgme/node_modules/jszip/lib/uint8ArrayWriter.js',
       function: 'Object.Uint8ArrayWriter',
       line: 11,
       method: 'Uint8ArrayWriter',
       native: false },
     { column: 22,
       file: '/home/sean.narenthiran/deepforge/node_modules/webgme/node_modules/jszip/lib/object.js',
       function: 'Object.out.generate',
       line: 823,
       method: 'out.generate',
       native: false },
     { column: 58,
       file: '/home/sean.narenthiran/deepforge/node_modules/webgme/src/server/middleware/blob/BlobBackendBase.js',
       function: null,
       line: 182,
       method: null,
       native: false },
     { column: 16,
       file: '/home/sean.narenthiran/deepforge/node_modules/graceful-fs/graceful-fs.js',
       function: null,
       line: 78,
       method: null,
       native: false },
     { column: 3,
       file: 'fs.js',
       function: 'FSReqWrap.readFileAfterClose [as oncomplete]',
       line: 380,
       method: 'readFileAfterClose [as oncomplete]',
       native: false } ],
  stack:
   [ 'RangeError: Invalid typed array length',
     '    at new Uint8Array (native)',
     '    at Object.Uint8ArrayWriter (/home/sean.narenthiran/deepforge/node_modules/webgme/node_modules/jszip/lib/uint8ArrayWriter.js:11:17)',
     '    at Object.out.generate (/home/sean.narenthiran/deepforge/node_modules/webgme/node_modules/jszip/lib/object.js:823:22)',
     '    at /home/sean.narenthiran/deepforge/node_modules/webgme/src/server/middleware/blob/BlobBackendBase.js:182:58',
     '    at /home/sean.narenthiran/deepforge/node_modules/graceful-fs/graceful-fs.js:78:16',
     '    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)' ] }
```

Something that may be useful is that there is around 6gb of space available on the cluster!

**Comment by SeanNaren** [comment]
The exported branch was fairly large and I assume this was why it crashed. Once I ported the `.deepforge/` folder to a larger HDD and updated the paths to point to the correct `.deepforge/` like [here](https://github.com/dfst/deepforge/wiki/Configuration) I was able to export!
